### ISSUE TITLE
Call out racy usage error somewhere

### ISSUE THREAD

**Issue by joncfoo** [wroge/scan#2]
Thanks for this library!  it minimizes the drudgery quite a bit 😅

I found myself wanting to DRY-up the column scanners across several queries since they returned the same shape of data.  I initially did the following:

```go
var myTableColumnScan = []scan.Column[MyTable]{
	scan.Any(func(l *MyTable, id int64) { l.ID = id }),
	// etc.
}

func QueryA(...) ... {
	...
	return scan.One[MyTable](row, myTableColumnScan...)
}


func QueryB(...) ... {
	...
	return scan.One[MyTable](row, myTableColumnScan...)
}
```

When I ran tests involving multiple queries using the same table column scanners I started noticing failures.  Upon further inspection and by using the `-race` flag I discovered that the slice of scanners was racy.

After changing the pattern to the following I noticed the tests passed and there were no more data races.

```go
func myTableColumnScan() []scan.Column[MyTable] {
	return []scan.Column[MyTable]{
		scan.Any(func(l *MyTable, id int64) { l.ID = id }),
		// etc.
	}
}

func QueryA(...) ... {
	...
	return scan.One[MyTable](row, myTableColumnScan()...)
}


func QueryB(...) ... {
	...
	return scan.One[MyTable](row, myTableColumnScan()...)
}
```

----

I understand this was my own error however I hope that perhaps this could be called out in the documentation somewhere.  WDYT?

**Comment by wroge** [comment]
Hi, thank you very much for your feedback.
Exactly, each 'Column' stores the value in a pointer. So it is not possible to use it in a meaningful way in parallel executions. But I am always open for suggestions!
I will add this to the documentation.

**Comment by wroge** [comment]
Hi Jonathan, thanks for your feedback.
I have added the 'Clone' method to the 'Column' interface so that every time 'All', 'Each' or 'One' are called, the 'Columns' are copied before being used.
I would be very grateful if you could try this out and see if it fixes your problems. (Update to version 0.0.6)
I have also updated the README. It is now a little easier to use the library. Thanks a lot!

**Comment by joncfoo** [comment]
Malte, thanks for incorporating my feedback and making the library even easier to use.  The README changes look good.  I reverted the changes in my code and there are no more racy conditions with the update.

Thanks once again!
